import{a as d,i as u,S}from"./assets/vendor-oevwmKEY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();d.defaults.baseURL="https://pixabay.com/api/";const f=async(e,t=1)=>{try{return(await d.get("",{params:{key:"45547752-43a0cb06c467be16aeef39c83",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:t}})).data}catch(a){console.error(a.message)}},h=(e,t)=>{const a=t.map(({webformatURL:i,largeImageURL:r,tags:s,likes:n,views:L,comments:v,downloads:x})=>`<li class="gallery-item">
        <a class="gallery-link" href="${r}">
          <img class="gallery-image" src="${i}" alt="${s}" />
        
        <ul class="info-list">
          <li class="info-item"><b>Likes</b>
          <span>${n}</span></li>
          <li class="info-item"><b>Views</b>
          <span>${L}</span></li>
          <li class="info-item"><b>Comments</b>
          <span>${v}</span></li>
          <li class="info-item"><b>Downloads
          <span></b>${x}</span></li>
        </ul>
        </a>
      </li>`).join("");e.insertAdjacentHTML("beforeend",a)},w=e=>{e.insertAdjacentHTML("afterend",'<span class="loader visible"></span>')},k=e=>e.innerHTML="",l=e=>u.error({message:e,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconUrl:"https://raw.githubusercontent.com/EevgenK/goit-js-hw-11/main/src/img/error.png",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),B=e=>u.warning({message:e,backgroundColor:"#4e75ff",messageColor:"#FAFAFB",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),y=e=>e.classList.add("visible"),m=e=>e.classList.remove("visible"),o={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".load")};let p=1,c="",g;const b=new S(".gallery a",{captionsData:"alt",captionDelay:250}),F=e=>{p+=1,y(g),f(c,p).then(({hits:t,totalHits:a})=>{h(o.gallery,t),b.refresh(),o.gallery.children.length===a&&(m(o.loadBtn),B("We're sorry, but you've reached the end of search results."))}).catch(t=>l("Ooops... Something go wrong. Please, try again later")).finally(()=>{m(g)})},P=e=>{e.preventDefault(),m(o.loadBtn);const t=e.currentTarget;if(c=t.input.value.trim(),!c)return l("There's nothing to search. Please, type the query target first!");w(o.loadBtn),g=document.querySelector(".loader"),k(o.gallery),f(c).then(({hits:a})=>{a.length>0?(h(o.gallery,a),b.refresh()):l("Sorry, there are no images matching your search query. Please try again!")}).then(()=>{y(o.loadBtn),o.loadBtn.addEventListener("click",F)}).catch(a=>l("Ooops... Something go wrong. Please, try again later")).finally(()=>{g.classList.remove("visible"),t.reset()})};o.form.addEventListener("submit",P);
//# sourceMappingURL=index.js.map
