import{a as p,i as u,S}from"./assets/vendor-oevwmKEY.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=i(t);fetch(t.href,a)}})();p.defaults.baseURL="https://pixabay.com/api/";const h=async(e,s,i=15)=>{try{return(await p.get("",{params:{key:"45547752-43a0cb06c467be16aeef39c83",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:i,page:s}})).data}catch(o){console.error(o.message)}},f=(e,s)=>{const i=s.map(({webformatURL:o,largeImageURL:t,tags:a,likes:l,views:L,comments:w,downloads:v})=>`<li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-image" src="${o}" alt="${a}" />
        
        <ul class="info-list">
          <li class="info-item"><b>Likes</b>
          <span>${l}</span></li>
          <li class="info-item"><b>Views</b>
          <span>${L}</span></li>
          <li class="info-item"><b>Comments</b>
          <span>${w}</span></li>
          <li class="info-item"><b>Downloads
          <span></b>${v}</span></li>
        </ul>
        </a>
      </li>`).join("");e.insertAdjacentHTML("beforeend",i)},x=e=>{e.insertAdjacentHTML("afterend",'<span class="loader visible"></span>')},B=e=>e.innerHTML="",d=e=>u.error({message:e,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconUrl:"https://raw.githubusercontent.com/EevgenK/goit-js-hw-11/main/src/img/error.png",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),k=e=>u.warning({message:e,backgroundColor:"#4e75ff",messageColor:"#FAFAFB",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),m=e=>e.classList.add("visible"),c=e=>e.classList.remove("visible"),r={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".load"),loader:""},P=15;let n=1,g="";const y=new S(".gallery a",{captionsData:"alt",captionDelay:250}),F=()=>{let e=r.gallery.firstChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})},b=(e,s)=>e/P/s,q=async()=>{try{const{hits:e,totalHits:s}=await h(g,n);if(c(r.loader),e.length<=0)return d("Sorry, there are no images matching your search query. Please try again!");b(s,n)>1&&m(r.loadBtn),f(r.gallery,e),y.refresh(),r.form.reset()}catch{d("Ooops... Something go wrong. Please, try again later")}},A=async()=>{try{const{hits:e,totalHits:s}=await h(g,n);b(s,n)<=1?(c(r.loadBtn),k("We're sorry, but you've reached the end of search results.")):m(r.loadBtn),f(r.gallery,e),y.refresh(),F()}catch{d("Ooops... Something go wrong. Please, try again later")}c(r.loader)},C=e=>{n+=1,c(r.loadBtn),m(r.loader),A()},H=e=>{if(e.preventDefault(),n=1,c(r.loadBtn),g=e.currentTarget.input.value.trim(),!g)return d("There's nothing to search. Please, type the query target first!");x(r.loadBtn),r.loader=document.querySelector(".loader"),B(r.gallery),q()};r.loadBtn.addEventListener("click",C);r.form.addEventListener("submit",H);
//# sourceMappingURL=index.js.map
