import{a as u,i as h,S}from"./assets/vendor-oevwmKEY.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();u.defaults.baseURL="https://pixabay.com/api/";const f=async(e,a)=>{try{return(await u.get("",{params:{key:"45547752-43a0cb06c467be16aeef39c83",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"15",page:a}})).data}catch(o){console.error(o.message)}},y=(e,a)=>{const o=a.map(({webformatURL:l,largeImageURL:t,tags:s,likes:n,views:L,comments:w,downloads:v})=>`<li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-image" src="${l}" alt="${s}" />
        
        <ul class="info-list">
          <li class="info-item"><b>Likes</b>
          <span>${n}</span></li>
          <li class="info-item"><b>Views</b>
          <span>${L}</span></li>
          <li class="info-item"><b>Comments</b>
          <span>${w}</span></li>
          <li class="info-item"><b>Downloads
          <span></b>${v}</span></li>
        </ul>
        </a>
      </li>`).join("");e.insertAdjacentHTML("beforeend",o)},x=e=>{e.insertAdjacentHTML("afterend",'<span class="loader visible"></span>')},B=e=>e.innerHTML="",c=e=>h.error({message:e,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconUrl:"https://raw.githubusercontent.com/EevgenK/goit-js-hw-11/main/src/img/error.png",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),k=e=>h.warning({message:e,backgroundColor:"#4e75ff",messageColor:"#FAFAFB",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px",theme:"dark"}),p=e=>e.classList.add("visible"),i=e=>e.classList.remove("visible"),r={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".load")};let d=1,g="",m;const b=new S(".gallery a",{captionsData:"alt",captionDelay:250}),F=()=>{let e=r.gallery.firstChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})},P=async()=>{try{const{hits:e}=await f(g,d);e.length>0?(y(r.gallery,e),b.refresh(),p(r.loadBtn)):c("Sorry, there are no images matching your search query. Please try again!")}catch{c("Ooops... Something go wrong. Please, try again later")}i(m),r.form.reset()},q=async()=>{try{const{hits:e,totalHits:a}=await f(g,d);y(r.gallery,e),b.refresh(),F(),r.gallery.children.length===a&&(i(r.loadBtn),k("We're sorry, but you've reached the end of search results."))}catch{c("Ooops... Something go wrong. Please, try again later")}i(m),p(r.loadBtn)},A=e=>{d+=1,i(r.loadBtn),p(m),q()},C=e=>{if(e.preventDefault(),d=1,i(r.loadBtn),g=e.currentTarget.input.value.trim(),!g)return c("There's nothing to search. Please, type the query target first!");x(r.loadBtn),m=document.querySelector(".loader"),B(r.gallery),P(),r.loadBtn.addEventListener("click",A)};r.form.addEventListener("submit",C);
//# sourceMappingURL=index.js.map
